controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
admin_timeslot_index:
    path: /admin/timeslots/{resource}
    controller: App\Controller\AdminTimeslotController::index
    requirements:
        resource: '\d+'